exclude: "^docs/|/migrations/|devcontainer.json"
default_stages: [pre-commit]

default_language_version:
  python: python{{ cookiecutter.python_version }}

repos:
  - repo: local
    hooks:
      - id: check-di-inject
        name: Validate DI inject/Provide usage
        entry: python libs/di/hooks/check_di_inject.py
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest-cov
        name: Run tests with coverage
        entry: make cov
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--tab-width", "2", "--single-quote"]
        exclude: "templates/"

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.24.0"
    hooks:
      - id: django-upgrade
        args: ["--target-version", "5.0"]

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format

  # Use uv to manage dependencies and requirements files
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.17
    hooks:
      # Update uv.lock file when pyproject.toml changes
      - id: uv-lock
      # Update requirements files
      - id: uv-export
        name: Update base requirements
        args:
          [
            --no-hashes,
            --no-header,
            --output-file,
            requirements/base.txt,
            --no-group,
            dev,
            --no-group,
            prod,
          ]
      - id: uv-export
        name: Update development requirements
        args:
          [
            --no-hashes,
            --no-header,
            --output-file,
            requirements/develop.txt,
            --group,
            dev,
          ]
      - id: uv-export
        name: Update production requirements
        args:
          [
            --no-hashes,
            --no-header,
            --output-file,
            requirements/production.txt,
            --group,
            prod,
          ]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.5.1"
    hooks:
      - id: pyproject-fmt

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
