[project]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.description }}"
authors = [
    {name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.email }}"}
]
readme = "README.md"
requires-python = ">={{ cookiecutter.python_version }}"
{%- if cookiecutter.open_source_license != 'Not open source' %}
license = "{{ cookiecutter.open_source_license }}"
{%- endif %}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: {{ cookiecutter.python_version }}",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
{%- if cookiecutter.open_source_license == 'MIT' %}
    "License :: OSI Approved :: MIT License",
{%- elif cookiecutter.open_source_license == 'BSD' %}
    "License :: OSI Approved :: BSD License",
{%- elif cookiecutter.open_source_license == 'GPLv3' %}
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
{%- elif cookiecutter.open_source_license == 'Apache Software License 2.0' %}
    "License :: OSI Approved :: Apache Software License",
{%- elif cookiecutter.open_source_license == 'Not open source' %}
    "Private :: Do Not Upload",
{%- endif %}
]
dependencies = [
  "django>=6.0.0",
  "django-environ>=0.12.0",
  "django-model-utils>=5.0.0",
  "django-extensions>=4.1.0",
  "djangorestframework>=3.15.0",
  "drf-nested-routers>=0.95",
  "drf-spectacular>=0.27.1",
  "loguru>=0.7.3",
  "djoser>=2.3.1",
  "djangorestframework-simplejwt>=5.3.1",
  "django-filter>=25.1.0",
  "stackprinter>=0.2.12",
  "dependency-injector>=4.46",
  "django-simple-history>=3.7",
  "django-mirage-field>=1.4",
  "pydantic>=2.10",
  "pydantic-settings>=2.7",
  {%- if cookiecutter.database_engine == 'postgres' %}
  "psycopg[binary]>=3.2.0",
  {%- elif cookiecutter.database_engine == 'mysql' %}
  "mysqlclient>=2.2.0",
  {%- endif %}
  {%- if cookiecutter.use_redis == "yes" %}
  "django-redis>=6",
  {%- endif %}
  {%- if cookiecutter.use_celery == "yes" %}
  "celery>=5.6.2",
  "django-celery-beat>=2.8.1",
  {%- endif %}
  {%- if cookiecutter.use_email == "yes" %}
  "jinja2>=3.1.4",
  {%- endif %}
]

[dependency-groups]
dev = [
  "coverage>=7.7.1",
  "django-coverage-plugin>=3.1.0",
  "django-debug-toolbar>=4.3.0",
  "django-silk>=5.1.0",
  "django-stubs>=5.2.8",
  "djangorestframework-stubs>=3.16.6",
  "mypy>=1.19.1",
  "pytest>=8.3.5",
  "pytest-cov>=6.0.0",
  "pytest-django>=4.10.0",
  "pytest-env>=1.1.5",
  "pytest-sugar>=1.0.0",
  "pytest-xdist>=3.6.1",
  "responses>=0.25.8",
  "ruff>=0.11.2"
  {%- if cookiecutter.use_redis == "yes" %},
  "fakeredis>=2.33"
  {%- endif %}
]
prod = [

]

[tool.ruff]
target-version = "py{{ cookiecutter.python_version|replace('.', '') }}"

line-length = 88
# Exclude a variety of commonly ignored directories.
extend-exclude = [
  "*/migrations/*.py",
  "protos/*",
  "staticfiles/*",
]
format.skip-magic-trailing-comma = false
lint.select = [
  "B",   # Bugbear potential errors
  "C4",  # comprehension optimization
  "DJ",  # Django dedicated rules
  "E",   # PEP8 basic errors
  "F",   # Pyflakes logical errors
  "I",   # import sorting
  "PGH", # Pytest dedicated rules
  "UP",  # new Python syntax upgrade
  "W",   # PEP8 warnings
]
lint.ignore = [
  "COM812", # Missing trailing comma in Python 3.6+ collection literals
  "DJ001",
  "DJ008",
  "ISC001", # Implicitly concatenated string literals on one line
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
  "S101",   # Use of assert detected https://docs.astral.sh/ruff/rules/assert/
  "SIM102", # sometimes it's better to nest
]
lint.exclude = [ "manage.py" ]
# The fixes in extend-unsafe-fixes will require
# provide the `--unsafe-fixes` flag when fixing.
lint.extend-unsafe-fixes = [
]
lint.isort.force-single-line = true

[tool.black]
line-length = 119
target-version = [ "py{{ cookiecutter.python_version|replace('.', '') }}" ]

[tool.djlint]
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
# TODO: remove T002 when fixed https://github.com/djlint/djLint/issues/687
ignore = "H006,H030,H031,T002"
include = "H017,H035"
indent = 2
max_line_length = 119
profile = "django"

[tool.django-stubs]
django_settings_module = "config.settings.test"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
plugins = [
  "mypy_django_plugin.main",
  "mypy_drf_plugin.main"
]
python_version = "{{ cookiecutter.python_version }}"
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
ignore_errors = true
# Django migrations should not produce any errors:
module = "*.migrations.*"

[tool.pytest]

[tool.pytest.ini_options]
addopts = """
    --no-migrations
    -v
    -n auto
    --reuse-db
    -x
    --tb=short
"""
env = [
  "DJANGO_READ_DOT_ENV_FILE=false",
  "DJANGO_SETTINGS_MODULE=config.settings.test"
]
python_files = ["test_*.py", "*_test.py", "tests.py"]

[tool.coverage]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "def __str__",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:"
]

[tool.coverage.run]
omit = [
  "*/migrations/*",
  "*/protos/*",
  "*/scripts/*",
  "*/tests/*",
  "*/admin.py",
  "*/apps.py",
  "config/*",
]
source = ["core", "apps"]

[tool.tomlsort]
all = false
in_place = true
no_sort_tables = false
sort_table_keys = true
sort_first = [
  "project",
  "dependency"
]
